branch-defaults:
  main:
    environment: cd12099-Full-Stack-Apps-AWS-dev
    group_suffix: null
environment-defaults:
  cd12099-Full-Stack-Apps-AWS-dev:
    branch: null
    repository: null
global:
  application_name: cd12099-Full-Stack-Apps-AWS
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
